---
name: Setup
description: Set up Go and the Task CLI.
runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e  # v7.0.0
      with:
        go-version-file: go.mod
    - name: Install Task
      uses: go-task/setup-task@a00fbb05ce67b35648be3c78cbc9fd85354c757e
