---
version: v2.12.2
name: custom-golangci-lint
plugins:
  - module: github.com/gostafa/coverlint
    import: github.com/gostafa/coverlint/plugin
    version: v0.0.5
  - module: github.com/gostafa/reusability
    import: github.com/gostafa/reusability/plugin
    version: v0.0.1
  - module: github.com/gostafa/distance
    import: github.com/gostafa/distance/plugin
    version: v0.0.1
  - module: github.com/gostafa/vulner
    import: github.com/gostafa/vulner/plugin
    version: v0.0.1
