---
actionlint: [internal/skipfiles]
adrs: [cargo]
ansible: [internal/skipfiles, uv]
bash-exec: []
bencher: []
biome/bun: [bun]
biome/node/fnm/npm: [npm/fnm]
biome/node/fnm/pnpm: [pnpm/fnm]
biome/node/fnm/yarn: [yarn/fnm]
biome/node/nvm/npm: [npm/nvm]
biome/node/nvm/pnpm: [pnpm/nvm]
biome/node/nvm/yarn: [yarn/nvm]
bruno/bun: [bun]
bruno/node/fnm/npm: [npm/fnm]
bruno/node/fnm/pnpm: [pnpm/fnm]
bruno/node/fnm/yarn: [yarn/fnm]
bruno/node/nvm/npm: [npm/nvm]
bruno/node/nvm/pnpm: [pnpm/nvm]
bruno/node/nvm/yarn: [yarn/nvm]
buf: [internal/skipfiles]
bun: []
cargo: [internal/skipfiles]
corepack/fnm: [fnm]
corepack/nvm: [nvm]
depcheck/bun: [bun]
depcheck/node/fnm/npm: [npm/fnm]
depcheck/node/fnm/pnpm: [pnpm/fnm]
depcheck/node/fnm/yarn: [yarn/fnm]
depcheck/node/nvm/npm: [npm/nvm]
depcheck/node/nvm/pnpm: [pnpm/nvm]
depcheck/node/nvm/yarn: [yarn/nvm]
djlint: [uv]
docker: []
dotenv-linter: [cargo, internal/skipfiles]
eslint/bun: [bun]
eslint/node/fnm/npm: [npm/fnm]
eslint/node/fnm/pnpm: [pnpm/fnm]
eslint/node/fnm/yarn: [yarn/fnm]
eslint/node/nvm/npm: [npm/nvm]
eslint/node/nvm/pnpm: [pnpm/nvm]
eslint/node/nvm/yarn: [yarn/nvm]
fnm: []
gh: [jq]
git: [gh]
go: [internal/skipfiles]
golangci-lint: [go, internal/skipfiles]
govulncheck: [go, internal/skipfiles]
hadolint: [internal/skipfiles]
htmlhint/node/fnm/npm: [npm/fnm]
htmlhint/node/fnm/pnpm: [pnpm/fnm]
htmlhint/node/nvm/npm: [npm/nvm]
htmlhint/node/nvm/pnpm: [pnpm/nvm]
internal/skipfiles: []
jq: []
jsonlint: [internal/skipfiles, uv]
knip/bun: [bun]
knip/node/fnm/npm: [npm/fnm]
knip/node/fnm/pnpm: [pnpm/fnm]
knip/node/fnm/yarn: [yarn/fnm]
knip/node/nvm/npm: [npm/nvm]
knip/node/nvm/pnpm: [pnpm/nvm]
knip/node/nvm/yarn: [yarn/nvm]
npm/fnm: [corepack/fnm, fnm]
npm/nvm: [corepack/nvm, nvm]
nvm: []
pnpm/fnm: [corepack/fnm, fnm]
pnpm/nvm: [corepack/nvm, nvm]
prettier/bun: [bun]
prettier/node/fnm/npm: [npm/fnm]
prettier/node/fnm/pnpm: [pnpm/fnm]
prettier/node/fnm/yarn: [yarn/fnm]
prettier/node/nvm/npm: [npm/nvm]
prettier/node/nvm/pnpm: [pnpm/nvm]
prettier/node/nvm/yarn: [yarn/nvm]
proto: [go]
protolint: [go, internal/skipfiles]
python: [uv]
rumdl: [uv]
shellcheck: [internal/skipfiles]
shfmt: [go, internal/skipfiles]
spectral/node/fnm/npm: [npm/fnm]
spectral/node/fnm/pnpm: [pnpm/fnm]
spectral/node/nvm/npm: [npm/nvm]
spectral/node/nvm/pnpm: [pnpm/nvm]
sqlfluff: [internal/skipfiles, uv]
stylelint/bun: [bun]
stylelint/node/fnm/npm: [npm/fnm]
stylelint/node/fnm/pnpm: [pnpm/fnm]
stylelint/node/fnm/yarn: [yarn/fnm]
stylelint/node/nvm/npm: [npm/nvm]
stylelint/node/nvm/pnpm: [pnpm/nvm]
stylelint/node/nvm/yarn: [yarn/nvm]
typescript/bun: [bun]
typescript/node/fnm/npm: [npm/fnm]
typescript/node/fnm/pnpm: [pnpm/fnm]
typescript/node/fnm/yarn: [yarn/fnm]
typescript/node/nvm/npm: [npm/nvm]
typescript/node/nvm/pnpm: [pnpm/nvm]
typescript/node/nvm/yarn: [yarn/nvm]
uv: []
vault: [jq]
yamllint: [internal/skipfiles, uv]
yarn/fnm: [corepack/fnm, fnm]
yarn/nvm: [corepack/nvm, nvm]
zizmor: [internal/skipfiles]
