---
version: '2'
run:
  timeout: 10m
linters:
  default: all
  disable: [wsl, gomodguard]
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
    depguard:
      rules:
        main:
          deny:
            - pkg: ^log$
              desc: use log/slog instead
            - pkg: ^fmt$
              desc: use fmt in development, but not in production code
    ireturn:
      allow: [anon, empty, error, generic, stdlib]
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
