---
version: "3.53"

output:
  group:
    begin: "::group::{{.TASK}}"
    end: "::endgroup::"
    error_only: false

silent: true

includes:
  actionlint: taskfiles/actionlint/Taskfile.yml
  adrs: taskfiles/adrs/Taskfile.yml
  ansible: taskfiles/ansible/Taskfile.yml
  bash-exec: taskfiles/bash-exec/Taskfile.yml
  bencher: taskfiles/bencher/Taskfile.yml
  biome: taskfiles/biome/Taskfile.yml
  bruno: taskfiles/bruno/Taskfile.yml
  buf: taskfiles/buf/Taskfile.yml
  bun: taskfiles/bun/Taskfile.yml
  cargo: taskfiles/cargo/Taskfile.yml
  corepack: taskfiles/corepack/Taskfile.yml
  depcheck: taskfiles/depcheck/Taskfile.yml
  djlint: taskfiles/djlint/Taskfile.yml
  docker: taskfiles/docker/Taskfile.yml
  dotenv-linter: taskfiles/dotenv-linter/Taskfile.yml
  eslint: taskfiles/eslint/Taskfile.yml
  fnm: taskfiles/fnm/Taskfile.yml
  gh: taskfiles/gh/Taskfile.yml
  git: taskfiles/git/Taskfile.yml
  go: taskfiles/go/Taskfile.yml
  hadolint: taskfiles/hadolint/Taskfile.yml
  htmlhint: taskfiles/htmlhint/Taskfile.yml
  jq: taskfiles/jq/Taskfile.yml
  jsonlint: taskfiles/jsonlint/Taskfile.yml
  knip: taskfiles/knip/Taskfile.yml
  npm: taskfiles/npm/Taskfile.yml
  nvm: taskfiles/nvm/Taskfile.yml
  pnpm: taskfiles/pnpm/Taskfile.yml
  prettier: taskfiles/prettier/Taskfile.yml
  proto: taskfiles/proto/Taskfile.yml
  protolint: taskfiles/protolint/Taskfile.yml
  python: taskfiles/python/Taskfile.yml
  rumdl: taskfiles/rumdl/Taskfile.yml
  shellcheck: taskfiles/shellcheck/Taskfile.yml
  shfmt: taskfiles/shfmt/Taskfile.yml
  spectral: taskfiles/spectral/Taskfile.yml
  sqlfluff: taskfiles/sqlfluff/Taskfile.yml
  staticcheck: taskfiles/staticcheck/Taskfile.yml
  stylelint: taskfiles/stylelint/Taskfile.yml
  typescript: taskfiles/typescript/Taskfile.yml
  uv: taskfiles/uv/Taskfile.yml
  vault: taskfiles/vault/Taskfile.yml
  yamllint: taskfiles/yamllint/Taskfile.yml
  yarn: taskfiles/yarn/Taskfile.yml
  zizmor: taskfiles/zizmor/Taskfile.yml

tasks:
  default:
    run: once
    desc: Show all available TaskOtter tasks
    cmds:
      - task --list-all

  lint:
    run: once
    desc: Run YAML and GitHub Actions lint checks
    deps:
      - yamllint:lint
      - zizmor:lint
      - actionlint:lint

  lint:fix:
    run: once
    desc: Auto-fix YAML lint issues
    deps:
      - yamllint:lint:fix

  fmt:
    run: once
    desc: Auto-format YAML files
    deps:
      - yamllint:lint:fix

  fmt:check:
    run: once
    desc: Check YAML formatting and style
    deps:
      - yamllint:lint

  ci:
    run: once
    desc: Run CI flow
    deps:
      - fmt:check
      - lint

  ci:fix:
    run: once
    desc: Run CI Fixing
    deps:
      - fmt
      - lint:fix
