// Taskotter 2026.
// SPDX-License-Identifier: Apache-2.0.

package tasksmoke

const (
	testEcho           = "echo"
	testPing           = "ping"
	testYamllint       = "yamllint"
	testSkipme         = "skipme"
	testGalaxyInstall  = "galaxy:install"
	testFileName       = "file"
	testFileBody       = "x\n"
	testChildName      = "child"
	testHelloFile      = "hello.txt"
	testBogusFlag      = "-bogus"
	testFamilyLeaf     = "family/leaf"
	testInternalShared = "internal/shared"
	testHiddenTask     = "_hidden"
	testSecretTask     = "secret"
	testMissingName    = "nope"
	testGo             = "go"
	testGit            = "git"
	testEslint         = "eslint"
	testEslintNPM      = "eslint/node/npm"
	testFmtCheck       = "fmt:check"
	testContinue       = "Continue?"
	testCI             = "ci"
	testAnsible        = "ansible"
	testLocked         = "locked"
	testKey            = "KEY"
	testVal            = "VAL"
	testSample         = "SAMPLE"
	testValue          = "value"
	testFOO            = "FOO"
	testBar            = "bar"
	testMissingTask    = "missing"
	testGOPKG          = "GO_PKG"
	testInstallPkg     = "install:pkg"
	testOneSecond      = "1s"
	testRepoSlash      = "/repo"
	testOther          = "other"
	testShortPath      = "x"
	testHiddenLint     = "_lint"
	testHostHome       = "/host-home"
	testTypecheck      = "typecheck"
)
