---
version: "3.5"

output:
  group:
    begin: "::group::{{.TASK}}"
    end: "::endgroup::"
    error_only: false

silent: true

includes:
  nix:
    taskfile: ../nix/Taskfile.yml

vars:
  JQ_NIX_INSTALLABLE: nixpkgs#jq

tasks:
  default:
    run: once
    desc: Show available jq automation tasks
    summary: Display the list of available jq-related tasks defined in this Taskfile.
    cmds:
      - task --list
