---
name: CI
description: Run the repository's own lint/format checks and go vet.
runs:
  using: composite
  steps:
    - name: Setup
      uses: $/.github/actions/setup
    - name: Run CI
      shell: bash
      run: task -t Taskfile.yml ci
    - name: Run Tests
      shell: bash
      run: |
        task -t Taskfile.yml go-junit-report:report GO_JUNIT_REPORT_IN=test-result.txt GO_JUNIT_REPORT_OUT=junit.xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f  # v7.0.0
      with:
        use_oidc: true
        files: ./coverage.out
        report_type: coverage
        name: coverage
        disable_search: false
        fail_ci_if_error: true
        verbose: true
    - name: Upload test results to Codecov
      uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f  # v7.0.0
      with:
        use_oidc: true
        report_type: test_results
        files: ./junit.xml
        disable_search: false
        name: go-test-results
        fail_ci_if_error: true
        verbose: true
