---
schema: taskotter.dev/taskfile-metadata/v1
module: ansible
taskfile: Taskfile.yml
exported_tasks:
  - galaxy:install
  - list:hosts
  - ping
  - run
  - syntax:check
  - vault:decrypt
  - vault:encrypt
