---
schema: taskotter.dev/taskfile-metadata/v1
module: ansible
taskfile: Taskfile.yml
exported_tasks:
  - ci
  - ci:fix
  - galaxy:install
  - install
  - install:undo
  - lint
  - lint:fix
  - list:hosts
  - ping
  - run
  - syntax:check
  - upgrade
  - vault:decrypt
  - vault:encrypt
  - version
